@extends('layouts.customer')

@section('title', 'Purchase Shares - ' . $shop->name)
@section('page-title', 'Investment Details')

@section('content')
<div class="max-w-5xl mx-auto">
    <div class="flex flex-col lg:flex-row gap-8">
        <!-- Details Column -->
        <div class="flex-1 space-y-8">
            <div class="bg-white rounded-[2.5rem] p-8 border border-slate-100 shadow-sm">
                <div class="flex items-center gap-4 mb-8">
                    <div class="w-16 h-16 rounded-2xl bg-sky-500/10 flex items-center justify-center text-3xl">🏢</div>
                    <div>
                        <h2 class="text-2xl font-black text-slate-800 leading-tight">{{ $shop->name }}</h2>
                        <p class="text-xs font-bold text-muted-light flex items-center gap-2 mt-1">
                            <span>📍</span> {{ $shop->location }}
                        </p>
                    </div>
                </div>

                <div class="prose prose-slate prose-sm mb-10">
                    <h3 class="text-xs font-black uppercase tracking-widest text-slate-400 mb-4">About Project</h3>
                    <p class="text-slate-600 font-medium leading-relaxed">
                        {{ $shop->description }}
                    </p>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-8">
                    <div class="p-5 rounded-3xl bg-slate-50 border border-slate-100">
                        <span class="text-[10px] font-black uppercase text-muted-light block mb-2">Share Price</span>
                        <div class="text-xl font-black text-slate-800">৳{{ number_format($shop->share_price, 2) }}</div>
                    </div>
                    <div class="p-5 rounded-3xl bg-slate-50 border border-slate-100">
                        <span class="text-[10px] font-black uppercase text-muted-light block mb-2">Inventory Surplus</span>
                        <div class="text-xl font-black text-emerald-600">{{ number_format($shop->available_shares) }} <span class="text-xs text-muted-light">Left</span></div>
                    </div>
                </div>

                <div class="p-6 rounded-3xl bg-sky-900 text-white relative overflow-hidden">
                    <div class="relative z-10">
                        <h4 class="text-sm font-black mb-1">Project Status</h4>
                        <p class="text-xs text-sky-200 font-bold mb-4">Funding progress for this chain shop.</p>
                        
                        @php $percent = (($shop->total_shares - $shop->available_shares) / $shop->total_shares) * 100; @endphp
                        <div class="w-full bg-white/10 h-3 rounded-full overflow-hidden mb-2">
                            <div class="bg-sky-400 h-full rounded-full transition-all duration-1000" style="width: {{ $percent }}%"></div>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-[10px] font-black">{{ number_format($percent, 1) }}% Funded</span>
                            <span class="text-[10px] font-black">{{ number_format($shop->total_shares - $shop->available_shares) }} shares sold</span>
                        </div>
                    </div>
                    <div class="absolute right-0 top-0 opacity-10 text-8xl rotate-12">📈</div>
                </div>
            </div>

            <!-- ROI Info -->
            <div class="bg-emerald-50 rounded-[2rem] p-8 border border-emerald-100">
                <div class="flex items-center gap-4 mb-4">
                    <span class="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center text-xl">💎</span>
                    <h3 class="font-black text-emerald-900 uppercase tracking-widest text-xs">Projected Dividends</h3>
                </div>
                <p class="text-emerald-800/70 text-sm font-medium leading-relaxed">
                    Investors receive a monthly share of the gross profit generated by this shop. Historical data suggests an annual yield of 12-18%. All distributions are automatically credited to your Commission Wallet.
                </p>
            </div>
        </div>

        <!-- Purchase Column -->
        <div class="w-full lg:w-[380px]">
            <div class="bg-white rounded-[2.5rem] p-8 border border-slate-100 shadow-xl sticky top-8">
                <h3 class="text-lg font-black text-slate-800 mb-6 flex items-center gap-3">
                    Buy Shares <span>⚡</span>
                </h3>

                <form action="{{ route('investments.purchase', $shop) }}" method="POST" id="purchaseForm" class="space-y-6">
                    @csrf
                    <div>
                        <label class="block text-[10px] font-black text-muted-light uppercase tracking-widest mb-3">Amount of Shares</label>
                        <div class="flex items-center gap-4 bg-slate-50 p-2 rounded-2xl border border-slate-100">
                            <button type="button" onclick="adjustShares(-1)" class="w-12 h-12 rounded-xl bg-white border border-slate-200 flex items-center justify-center text-xl font-bold hover:bg-slate-100 transition shadow-sm">-</button>
                            <input type="number" name="shares" id="sharesInput" value="1" min="1" max="{{ $shop->available_shares }}" class="flex-1 bg-transparent border-none text-center font-black text-xl text-slate-800 focus:ring-0">
                            <button type="button" onclick="adjustShares(1)" class="w-12 h-12 rounded-xl bg-white border border-slate-200 flex items-center justify-center text-xl font-bold hover:bg-slate-100 transition shadow-sm">+</button>
                        </div>
                    </div>

                    <div class="p-6 rounded-2xl bg-slate-50 border border-slate-100 space-y-4">
                        <div class="flex justify-between items-center text-xs font-bold text-muted-light">
                            <span>Subtotal</span>
                            <span class="text-slate-800" id="subtotalDisplay">৳{{ number_format($shop->share_price, 2) }}</span>
                        </div>
                        <div class="flex justify-between items-center text-xs font-bold text-muted-light">
                            <span>Platform Fee</span>
                            <span class="text-slate-800">৳0.00</span>
                        </div>
                        <div class="pt-4 border-t border-slate-200 flex justify-between items-center">
                            <span class="text-sm font-black text-slate-800">Total</span>
                            <span class="text-xl font-black text-sky-600" id="totalDisplay">৳{{ number_format($shop->share_price, 2) }}</span>
                        </div>
                    </div>

                    @php $mainWallet = auth()->user()->getWallet('main'); @endphp
                    <div class="flex items-center gap-3 px-4 py-3 bg-sky-50 rounded-xl border border-sky-100">
                        <span class="text-lg">👛</span>
                        <div>
                            <p class="text-[9px] font-black text-sky-800 uppercase leading-none mb-1">Main Wallet Balance</p>
                            <p class="text-sm font-black text-sky-600">৳{{ number_format($mainWallet ? $mainWallet->balance : 0, 2) }}</p>
                        </div>
                    </div>

                    <button type="button" onclick="confirmPurchase()" class="w-full bg-sky-600 hover:bg-sky-500 text-white font-black py-5 rounded-2xl flex items-center justify-center gap-3 transition-all hover:scale-[1.02] shadow-xl shadow-sky-600/20">
                        Finalize Purchase <span>🤝</span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    const price = {{ $shop->share_price }};
    const maxShares = {{ $shop->available_shares }};
    const balance = {{ $mainWallet ? $mainWallet->balance : 0 }};

    function updateCalculations() {
        const shares = parseInt(document.getElementById('sharesInput').value) || 0;
        const total = shares * price;
        
        document.getElementById('subtotalDisplay').innerText = '৳' + total.toLocaleString(undefined, {minimumFractionDigits: 2});
        document.getElementById('totalDisplay').innerText = '৳' + total.toLocaleString(undefined, {minimumFractionDigits: 2});
    }

    function adjustShares(val) {
        let current = parseInt(document.getElementById('sharesInput').value) || 0;
        current += val;
        if(current < 1) current = 1;
        if(current > maxShares) current = maxShares;
        document.getElementById('sharesInput').value = current;
        updateCalculations();
    }

    document.getElementById('sharesInput').addEventListener('input', updateCalculations);

    function confirmPurchase() {
        const shares = parseInt(document.getElementById('sharesInput').value);
        const total = shares * price;

        if (total > balance) {
            Swal.fire({
                icon: 'error',
                title: 'Insufficient Balance',
                text: 'Your main wallet does not have enough funds to complete this purchase.',
                confirmButtonColor: '#3b82f6',
            });
            return;
        }

        Swal.fire({
            title: 'Confirm Purchase',
            text: `You are about to buy ${shares} shares in {{ $shop->name }}. Total: ৳${total.toLocaleString()}. Are you sure?`,
            icon: 'question',
            showCancelButton: true,
            confirmButtonColor: '#3b82f6',
            cancelButtonColor: '#94a3b8',
            confirmButtonText: 'Yes, Purchase!',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('purchaseForm').submit();
            }
        });
    }
</script>
@endsection
